# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distribute APK to Firebase App Distribution (CI)"
  lane :distribute do |options|
    build_path = options[:build_path]

      firebase_app_distribution(
          app: "1:855172212777:android:634cb8cf158ce777b11438",
          testers: "hebert.albertin@tembici.com, dsena.m@hotmail.com", "douglas.conceicao@tembici.com","janaina.barbosa@tembici.com", "guilherme.baldissera@tembici.com",
          release_notes: "Lots of amazing new features to test out!",
          firebase_cli_token: "1//0hSnXXyvNeVHMCgYIARAAGBESNwF-L9Ir53uLLI5e5yJRNy3TZZrsVkPIhzn0xnYvoiCaTsDdGwM4YvMh_yDfbBLnp3dn7SuoDLQ",
          apk_path: build_path
      )

  end
end
