# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "My awesome app"
  lane :distribute do
    gradle(task: "clean assembleRelease")

      firebase_app_distribution(
          app: "1:855172212777:android:634cb8cf158ce777b11438",
          testers: "hebert.albertin@tembici.com, dsena.m@hotmail.com",
          release_notes: "Lots of amazing new features to test out!"
      )

  end
end
